config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :meetings
  resources :bookings, except: [:index, :new]

  post "payment-intent", to: "bookings#intent"
  get ":booking_link", to: "users#show", as: :user

  scope '/:booking_link', as: :user do
    resources :bookings, only: [:index, :new]
  end
  resources :webhooks, only: :create
  
  root to: "home#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_many :bookings
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = current_user.meetings
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = current_user.meetings.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = current_user.meetings.new(meeting_params.merge(user: current_user))

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to root_path, notice: "Meeting was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Meeting was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :location, :description, :color, :duration, :payment_required, :price)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def duration(type)
    if type.duration == 60
      "1 hr"
    else
      type.duration.to_formatted_s + " mins"
    end
  end
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
<% if meeting.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% meeting.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :location, class: label_class %>
          <%= form.text_field :location, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :description, class: label_class %>
          <%= form.rich_text_area :description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :color, class: label_class %>
          <%= form.text_field :color, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :duration, class: label_class %>
          <%= form.number_field :duration, class: input_class %>
      </div>
  <div class="mb-6 flex items-center">
    <%= form.check_box :payment_required, class: checkbox_class %>
        <%= form.label :payment_required, class: label_class %>
      </div>
  <div class="mb-6 lg:w-1/4">
        <%= form.label :price, class: label_class %>
          <%= form.number_field :price, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if meeting.persisted? %>
<%= link_to "Cancel", meeting, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", meetings_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <%= link_to edit_meeting_path(meeting), class: "p-6 border shadow-xl
  rounded-xl block hover:shadow-lg transition ease-in duration-300 relative
  overflow-hidden" do %>
  <div
    class="h-1 w-full absolute top-0 left-0 right-0"
    style="background-color: <%= meeting.color %>"
  ></div>
  <h3 class="fon-medium text-2xl"><%= meeting.name %></h3>
  <p class="text-gray-500">View booking page</p>
  <p><%= duration(meeting) %></p>

  <% if meeting.payment_required? %>
  <div class="mt-3 pt-3 border-t">
    <p><strong>Payment required</strong></p>
    <p><strong>Price: </strong><%= number_to_currency(meeting.price) %></p>
  </div>
  <% end %> <% end %>
</div>

app/views/meetings/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit meeting</h1>
    <% if @meeting.persisted? %>
    <%= button_to 'Destroy', @meeting, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Meetings</h1>

    <%= link_to new_meeting_path, class: button_class(theme: "primary") do %>
    Add New Meeting
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Location</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Color</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Duration</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Payment required</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Price</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">User</th>
                
      </tr>
    </thead>

    <tbody>
      <% @meetings.each do |meeting| %>
      <%= content_tag :tr, id: dom_id(meeting), class: dom_class(meeting) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to meeting.name, meeting %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= meeting.location %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= meeting.description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= meeting.color %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= meeting.duration %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= meeting.payment_required %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= meeting.price %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= meeting.user %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/meetings/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="font-bold text-3xl mb-6">New meeting</h1>
    <% if current_user.booking_link? %> <%= link_to "View live page",
    user_path(booking_link: current_user.booking_link), class: "text-gray-700
    underline" %> <% end %>
  </div>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Meeting</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to meetings_path, class: button_class(theme: "transparent") do %>
      All Meetings
      <% end %>
      <%= link_to edit_meeting_path(@meeting), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @meeting.name %></p>
      </li>
      <li>
        <p class="font-semibold">Location:</p>
        <p><%= @meeting.location %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @meeting.description %></p>
      </li>
      <li>
        <p class="font-semibold">Color:</p>
        <p><%= @meeting.color %></p>
      </li>
      <li>
        <p class="font-semibold">Duration:</p>
        <p><%= @meeting.duration %></p>
      </li>
      <li>
        <p class="font-semibold">Payment required:</p>
        <p><%= @meeting.payment_required %></p>
      </li>
      <li>
        <p class="font-semibold">Price:</p>
        <p><%= @meeting.price %></p>
      </li>
      <li>
        <p class="font-semibold">User:</p>
        <p><%= @meeting.user %></p>
      </li>
  </ul>
</div>